import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header";
import { Locale, Languages } from "@/lang/languages";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return Languages.locales.map((lang) => ({ lang }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang}>
      <head>
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Header lang={lang} />
        <div>{children}</div>
      </body>
    </html>
  );
}
